### ISSUE TITLE
Blueprint Assets Issues

### ISSUE THREAD

**Issue by muhammadmoizulhaq** [lucoiso/UEProject_Elementus#28]
All the assets are showing in the explorer but did not open in the unreal editor.
![Screenshot 2022-10-14 161357](https://user-images.githubusercontent.com/29840623/195833898-6bc0764b-3fc6-4d88-a921-9bc7e7515137.png)
![Screenshot 2022-10-14 161139](https://user-images.githubusercontent.com/29840623/195833911-958af585-b2bd-4e36-b684-8d8cdc6e72cf.png)
![Screenshot 2022-10-14 161157](https://user-images.githubusercontent.com/29840623/195833913-b3bb92dc-d208-4c8e-a20d-d6c4bfbe8e1e.png)
![Screenshot 2022-10-14 161300](https://user-images.githubusercontent.com/29840623/195833917-65e733dd-c16c-445c-bb9f-86a44b84f14f.png)
![Screenshot 2022-10-14 161311](https://user-images.githubusercontent.com/29840623/195833920-7697344b-ef92-420c-becf-6a5888e907b2.png)

**Comment by lucoiso** [comment]
Hi! @mmoizulhaq 

If you're cloning this repository with Git, ensure that you have Git LFS installed.

If you're downloading the project, unfortunately the Github's "Download Zip" function doesn't work with Unreal Engine project due to the size of the files. That's the same reason we need to use the Git LFS (Large File Storage).

When we try to clone or download without Git LFS installed, all assets got corrupted (as you can see in the folder, all files have only 1kb) and the engine don't show them :S.

Download the project from the [Releases Page](https://github.com/lucoiso/UEProject_Elementus/releases) or clone using git (with LFS installed): https://git-lfs.github.com/

---

If the problem persists even with Git LFS, let me know! :)

**Comment by muhammadmoizulhaq** [comment]
Thanks for helping out
I will let you know, if I stuck any where else.
